name: Build/test/lint/CodeQL Host Plugin

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false # continue testing on all platforms even if one fails
    steps:
      - uses: actions/checkout@v3
      # TODO: Add CodeQL setup here

      # We depend on the Hosts package, but it is not published yet
      # So for now let's build it here too and link it like we do on local workstation
      # From here down to the 'END HOSTS SETUP' token below, we can delete once that package is published
      - uses: actions/checkout@v3
        with:
          repository: "aws-samples/amazon-sumerian-hosts"
          ref: "mainline2.0"
          path: "hosts"
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
        working-directory: "./hosts"
      - run: npm run build
        working-directory: "./hosts"
      # The babylon hosts package isn't published yet, so for now we install it
      # from a local checkout so our references work during the build
      - run: npm install ../hosts/packages/amazon-sumerian-hosts-babylon
        working-directory: "./open-source-hosts-plugin"
      # END HOSTS SETUP

      # Write the commit hash into the script file, so we get the git hash in the built artifacts
      # Believe it or not, the following perl statement works on ubuntu/windows/macos
      - name: "Set version number"
        run: |
          perl -i -p -e "s/PLUGIN_VERSION = .*/PLUGIN_VERSION = '${{ github.sha }}';/" ${{ github.workspace }}/open-source-hosts-plugin/scripts/sumerianhost.ts
      - run: npm install
        working-directory: "./open-source-hosts-plugin"
      - run: npm run release
        working-directory: "./open-source-hosts-plugin"
      # TODO: Perform CodeQL Analysis here
